// Assignment Code
var generateBtn = document.querySelector("#generate");

var passwordText = document.querySelector("#password");
passwordText.value = password;







// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);

function generatePassword() {
  var upperCase = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];
var lowerCase = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
var numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
var spCha = ['!', '$', '%', '&', '@', '#', '^', '*'];
var passwordLength = 0
//push user selections for criteria from arrays to workingArray for random selection
var myWorkingArray = [];
//resultsArray will be the password randomly generated by computer based on user selections myWorkingArray(user selected criteria)
var resultsArray = []; 

// confirms and prompts for user to select criteria for password. 
var starterQuestion = confirm("Let's set up your password criteria.");
if (starterQuestion) {

  lengthPassword = prompt("Choose length of password between 8 and 128 characters.");
  console.log(lengthPassword);
  if (lengthPassword < 8 || lengthPassword > 128) {
    prompt("Choose length of password between 8 and 128 characters.");
  }
} else {
  confirm("Let's set up your password criteria.");
  return;
}
}